In [1]:
import torch
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt

In [2]:
class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        
        self.layer1 = nn.Linear(1, 5)
        self.layer2 = nn.Linear(5, 5)
        self.layer3 = nn.Linear(5, 1)

    def forward(self, x):
        x = torch.tanh(self.layer1(x))
        x = torch.tanh(self.layer2(x))
        x = self.layer3(x)
        
        return x

In [3]:
np.random.seed(42)
model = Model()
loss_func = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

x = torch.linspace(0, 1, 100).reshape(-1,1)
y = x**2 + 1

In [4]:
y_pred = model.forward(x)
loss = loss_func(y, y_pred)
loss.backward()

for param in model.parameters():
    print(param.grad)

tensor([[-0.1909],
        [ 0.1448],
        [-0.0270],
        [ 0.0481],
        [-0.0552]])
tensor([-0.3353,  0.2490, -0.0409,  0.0830, -0.0918])
tensor([[-2.0228e-01,  3.3673e-01,  3.0743e-01, -4.3054e-01,  7.6364e-03],
        [ 1.1377e-02, -1.8247e-02, -1.6219e-02,  2.3298e-02, -9.6927e-04],
        [-1.5194e-03,  2.4748e-03,  2.2237e-03, -3.1617e-03,  1.0077e-04],
        [ 3.7025e-02, -6.3285e-02, -5.8775e-02,  8.0990e-02, -1.5223e-04],
        [-9.7220e-02,  1.6356e-01,  1.5031e-01, -2.0920e-01,  2.4166e-03]])
tensor([-0.6766,  0.0364, -0.0050,  0.1277, -0.3293])
tensor([[ 0.3620,  0.8166,  1.1022,  1.1993, -0.7390]])
tensor([-1.7354])
