In [20]:
import torch
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt

In [27]:
class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        
        self.layer1 = nn.Linear(1, 5)
        self.layer2 = nn.Linear(5, 5)
        self.layer3 = nn.Linear(5, 1)

    def forward(self, x):
        x = torch.tanh(self.layer1(x))
        x = torch.tanh(self.layer2(x))
        x = self.layer3(x)
        
        return x

In [28]:
np.random.seed(42)
model = Model()
loss_func = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

x = torch.linspace(0, 1, 100).reshape(-1,1)
y = x**2 + 1

In [29]:
y_pred = model.forward(x)
loss = loss_func(y, y_pred)
loss.backward()

for param in model.parameters():
    print(param.grad)

tensor([[-0.0020],
        [ 0.2458],
        [ 0.2205],
        [-0.0748],
        [ 0.0554]])
tensor([-0.0136,  0.4795,  0.4159, -0.1436,  0.0930])
tensor([[-0.2891,  0.4981,  0.2787, -0.5411, -0.2976],
        [ 0.1822, -0.3135, -0.1769,  0.3387,  0.1974],
        [-0.5019,  0.8637,  0.4875, -0.9325, -0.5459],
        [ 0.1702, -0.2930, -0.1645,  0.3175,  0.1791],
        [ 0.4985, -0.8576, -0.4844,  0.9255,  0.5443]])
tensor([ 0.7012, -0.4385,  1.2071, -0.4113, -1.1980])
tensor([[-1.6175, -1.1434,  0.3350,  1.9913,  0.1950]])
tensor([-3.1928])
