In [158]:
import numpy as np
import qiskit as qk
import matplotlib.pyplot as plt
from qiskit import Aer
from tqdm.notebook import tqdm

import sys
sys.path.insert(0, '../../src/')
from neuralnetwork import *
from analysis import *
from data_encoders import *
from parametrizations import *

#%matplotlib notebook
%matplotlib inline
%load_ext autoreload
%autoreload 2

np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [178]:
backend = Aer.get_backend('qasm_simulator')
n_samples = 4
n_features = 3
n_targets = 1

model = ParallelModel(n_features=n_features,
                      n_targets=n_targets,
                      reps=reps,
                      backend=backend, 
                      shots=100000)

x = np.random.uniform(0, np.pi/2, (n_samples, n_features))
y = np.array([[0.2], [0.8], [1.6], [2.]])

print(model.theta)
print(x)
print(y.flatten())

[5.230 1.334 1.142 1.152 1.912 3.297 2.714 1.830 3.844 0.876 1.836 2.302]
[[0.716 1.233 0.314]
 [0.808 0.931 0.073]
 [0.954 0.268 0.102]
 [1.491 1.517 1.270]]
[0.200 0.800 1.600 2.000]


In [179]:
reps = 4
np.random.seed(42)
model = ParallelModel(n_features=n_features,
                      n_targets=n_targets,
                      reps=reps,
                      backend=backend, 
                      shots=100000)

In [ ]:
optimizer = Adam()
optimizer.initialize(model.theta.shape)

for i in tqdm(range(200)):
    grad = [model.gradient(x, y)]
    grad = optimizer(grad)
    model.theta += -0.05*grad[0]
    y_pred = model.predict(x)
    loss = model.loss(x,y)
    print(f"{loss=:.3f}, {y_pred.flatten()=}")

  0%|          | 0/200 [00:00<?, ?it/s]

loss=0.428, y_pred.flatten()=array([1.781, 1.871, 1.757, 1.377])
loss=0.371, y_pred.flatten()=array([1.653, 1.768, 1.693, 1.346])
loss=0.321, y_pred.flatten()=array([1.536, 1.657, 1.644, 1.301])
loss=0.282, y_pred.flatten()=array([1.406, 1.554, 1.603, 1.249])
loss=0.255, y_pred.flatten()=array([1.274, 1.452, 1.557, 1.180])
loss=0.231, y_pred.flatten()=array([1.160, 1.350, 1.529, 1.127])
loss=0.213, y_pred.flatten()=array([1.049, 1.263, 1.499, 1.085])
loss=0.202, y_pred.flatten()=array([0.965, 1.197, 1.497, 1.067])
loss=0.198, y_pred.flatten()=array([0.902, 1.149, 1.498, 1.064])
loss=0.196, y_pred.flatten()=array([0.872, 1.128, 1.521, 1.091])
loss=0.196, y_pred.flatten()=array([0.862, 1.124, 1.547, 1.117])
loss=0.198, y_pred.flatten()=array([0.876, 1.124, 1.579, 1.155])
loss=0.200, y_pred.flatten()=array([0.886, 1.140, 1.602, 1.202])
loss=0.202, y_pred.flatten()=array([0.904, 1.153, 1.623, 1.247])
loss=0.200, y_pred.flatten()=array([0.923, 1.158, 1.624, 1.289])
loss=0.202, y_pred.flatte

In [100]:
print(model.predict(x))

[[0.595835330329655], [0.5495493202923394], [0.6471920352251825], [0.5200385989089172]]
